feat: on each insert/remove from the shelf, the DB is update accordingly
nicolasfara/smart-shelf-rpi pull request #24
Opened 2022-01-31 11:31 UTC by nicolasfara

2022-01-31 16:30 UTC, nicolasfara commented on models/product.py
> +class Product(BaseModel):
@sonatype-lift ignore

2022-01-31 16:30 UTC, nicolasfara commented on models/product.py
> +class Product(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class Product(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class Product(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class ProductTag(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class Product(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class Product(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class ProductTag(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class Product(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class Product(BaseModel):
@sonatype-lift ignore

2022-01-31 16:31 UTC, nicolasfara commented on models/product.py
> +class ProductTag(BaseModel):
@sonatype-lift ignore

2022-02-02 11:31 UTC, vitlinda requested changes
Check the doc

2022-02-05 09:14 UTC, vitlinda approved these changes

2022-02-05 09:14 UTC, merged